### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by rollsover** [egal/installer#4]

**Comment by annstgn** [comment]
Также скрипт предлагает ввести имя проекта такой строкой: Inter project name. Вместо Enter

Добавление нового сервиса после первоначального разворота

Баг или фича: при нажатии стрелки назад возвращаешься на главную страницу.

Рассмотреть ситуацию дублирования имен сервисов - что такой сервис уже есть.
Написать инструкцию для мака
Добавить опцию: auth-service коробочный или конфигурируемый
Убрать конкатенацию -service справа к имени добавляемых сервисов

**Comment by annstgn** [comment]
Возможно стоит добавить выбор директории для установки

**Comment by vedorofeev** [comment]
Добавить инсталлер в .gitignore, в .dockerignore

**Comment by vedorofeev** [comment]
Добавить обработку ошибок и повторную отправку запроса при неудачном клонировании из гита

**Comment by annstgn** [comment]
![image](https://user-images.githubusercontent.com/91238426/172772029-61ab4345-3d72-4653-95b5-c9f8afcb7742.png)

**Comment by vedorofeev** [comment]
> ![image](https://user-images.githubusercontent.com/91238426/172772029-61ab4345-3d72-4653-95b5-c9f8afcb7742.png)

Не удалось воспроизвести
