### ISSUE TITLE
UX при первом использовании очень плохой.

### ISSUE THREAD

**Issue by rollsover** [egal/installer#5]

**Comment by rollsover** [comment]
Ирина К. пользовалась, получилось с третей попытки, так как нажимала не то или не понимала, что нажимать.

**Comment by PolinaFarlie** [comment]
Протестила с Аней и опросила Иру. Нет проблем с UX, а Ира просто нечаянно нажала не то, проблемы понимания у нее нет, и даже мне там понятно, что делать=)

**Comment by rollsover** [comment]
Ну, ладно
